# Generated by Django 2.0.4 on 2018-09-06 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=5)),
                ('height', models.CharField(blank=True, max_length=5)),
                ('weight', models.IntegerField(default=150)),
                ('birth_date', models.CharField(blank=True, max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(blank=True, max_length=30)),
                ('season', models.IntegerField(default=1900)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='player_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Team'),
        ),
    ]
