# Generated by Django 2.0.6 on 2019-01-17 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_profile_teams'),
        ('teams', '0003_remove_team_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Profile'),
        ),
    ]
