# Generated by Django 2.0.6 on 2019-01-17 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_team_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Profile'),
        ),
    ]
