# Generated by Django 2.0.4 on 2018-05-03 04:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0002_auto_20180501_0457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='user2',
        ),
        migrations.AddField(
            model_name='game',
            name='opponent_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='own_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
