# Generated by Django 2.0.4 on 2018-05-06 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20180503_0449'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='lineups_set',
            field=models.BooleanField(default=False),
        ),
    ]
