# Generated by Django 2.0.4 on 2018-05-09 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_lobby_lineups_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
