# Generated by Django 2.0.4 on 2018-05-09 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_game_is_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='lineups_set',
            field=models.BooleanField(default=False),
        ),
    ]
