# Generated by Django 2.0.4 on 2018-05-12 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_game_lineups_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_id',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
