# Generated by Django 2.0.6 on 2018-08-29 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_game_game_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_id',
            field=models.IntegerField(default=0),
        ),
    ]
