# Generated by Django 2.0.6 on 2019-01-16 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_remove_team_profile'),
        ('user', '0002_profile_teams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='teams',
        ),
        migrations.AddField(
            model_name='profile',
            name='teams',
            field=models.ManyToManyField(null=True, to='teams.Team'),
        ),
    ]
