# Generated by Django 2.0.4 on 2018-04-25 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Profile'),
        ),
    ]
