# Generated by Django 2.0.6 on 2019-01-16 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190116_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='teams',
            field=models.ManyToManyField(to='teams.Team'),
        ),
    ]
